<a href="https://colab.research.google.com/github/bobantonbob/ANMAelectric/blob/master/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1_Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:

vector = list(range(1, 11))
print(vector)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2_Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
import numpy as np
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3_Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[3 5 8 3 4]
 [8 2 4 8 6]
 [5 1 5 2 8]
 [4 6 9 6 4]
 [5 1 4 4 2]]


4_Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.